services:
  artgraph:
    build: .
    image: artgraph
    ports:
      - "8000:8000"
    user: isagog
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level ${LOG_LEVEL:-info}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"

# if the env var is not set it will use INFO
# to override you can
# LOG_LEVEL=debug docker-compose up
